### PR TITLE
WIP: Make UI more responsive

### LINKED ISSUE #20: Make the UI responsive

### PR DESCRIPTION
**Pull request by chrisjm**
## Overview
While working on the responsive UI, I went down a rabbit hole of reorganizing the styles into a separate folder. 

The purpose of this was to:

1. Clean up the components
2. Allow for reusing shared styles

I know this is a big change, so I'm definitely open to feedback. 

## Tasks
- [ ] Move mobile links to top of page
- [x] Collapse the Profile dropdown menu into MenuLinks
- [x] Reorganize styles into a directory

## Screenshots

pairhub-responsive-ui

## Issues

Fixes #20

### CODE REVIEW

**Comment by treyles** [comment]
Good idea collapsing the profile dropdown into MenuLinks!

The placement of the links is a little awkward to me though — particularly the Log-out button, and the user potentially having to scroll through several posts to access Chat and Source.

What do you think about putting all the links in one row above the search bar? This makes all the links easily accessible and puts the Log-out button where users expect it to be. 

pairhubmock

**Comment by chrisjm** [comment]
@treyles I like it! Thanks for making the mockup.

**Comment by gustavlrsn** [comment]
Great work on this @chrisjm! I think the styles organization looks clean, let's try it out like this and see how we like it 🙂 

Also, nice mockup @treyles, looks great.

Found a tiny spacing issue in the profile dropdown:
image

**Comment by chrisjm** [comment]
Closing in favor of #43

**Pull request closed without merging**
