### PR TITLE
Share post

### PR DESCRIPTION
**Pull request by treyles**
Add feature #8 

### Tasks

- [x] Twitter share popup
- [x] Auto populate tweet with post content, links, hashtags
- [x] Truncate content > 280 characters
- [x] Facebook share popup

### CODE REVIEW

**Comment by treyles** [comment]
I leveraged the library PairHub currently uses for tooltips (Tippy) to house the Twitter and Facebook buttons:

feb-26-2019 01-44-54

The generated sample Tweet:

screen shot 2019-02-26 at 1 18 33 am

Open to feedback and any changes of course! 😊

**Comment by gustavlrsn** [comment]
Thank you for the PR, great stuff! 

There is actually a direct link to posts that could make sense to use, for example: https://pairhub.io/post/5c16a8de636dfb0062f212b1 (using the id of the post). Although that url is a bit uglier, and longer. 🤔 What do you think? 

There is also a hashtag on twitter #pairwithme (once popularized by http://www.pairprogramwith.me/) that I think could be nice to use and revive a little bit, as it's more focused around the idea of finding a pair, instead of #pairprogramming. Thoughts?

**Comment by treyles** [comment]
@gustavlrsn changes made!

> There is actually a direct link to posts

Ah, didn't realize there was a route to posts — definitely makes more sense. Twitter shortens links anyway so the length doesn't matter.

> #pairwithme

I like it!

**Comment by gustavlrsn** [comment]
@treyles merging! 👍

**Pull request merged**
